AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FraudQueue:
   Type: AWS::SQS::Queue
   Properties:
    QueueName: fraud-score-queue
    VisibilityTimeout: 180

  FraudResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fraud-results
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
   
  FraudScoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      MemorySize: 2048
      Architectures:
        - x86_64
      Environment:
        Variables:
          RESULTS_TABLE_NAME: !Ref FraudResultsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FraudResultsTable
      Events:
        FraudQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FraudQueue.Arn
            BatchSize: 1

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: fraud-scoring-python31
      
Outputs:
  FraudQueueUrl:
    Description: URL da fila SQS
    Value: !Ref FraudQueue

  FraudQueueArn:
    Description: ARN da fila SQS
    Value: !GetAtt FraudQueue.Arn

  FraudResultsTableName:
    Description: Tabela DynamoDB fraud-results
    Value: !Ref FraudResultsTable

  FraudScoringFunctionArn:
    Description: ARN da Lambda
    Value: !GetAtt FraudScoringFunction.Arn