AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FraudScoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      MemorySize: 1024
      Architectures:
        - x86_64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: fraud-scoring-python314
