AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AlertEmail:
    Type: String
    Default: "seu_email@gmail.com"
    Description: E-mail opcional para receber alertas de fraude via SNS.

Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, ""]]

Resources:
  FraudQueue:
   Type: AWS::SQS::Queue
   Properties:
    QueueName: fraud-score-queue
    VisibilityTimeout: 180

  FraudResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fraud-results
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH

  FraudAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: fraud-alerts

  FraudAlertsEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlertEmail
    Properties:
      Protocol: email
      Endpoint: !Ref AlertEmail
      TopicArn: !Ref FraudAlertsTopic
   
  FraudScoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      MemorySize: 2048
      Architectures:
        - x86_64
      Environment:
        Variables:
          RESULTS_TABLE_NAME: !Ref FraudResultsTable
          SNS_TOPIC_ARN: !Ref FraudAlertsTopic
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FraudResultsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FraudAlertsTopic.TopicName
      Events:
        FraudQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FraudQueue.Arn
            BatchSize: 1

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: fraud-scoring-python31
      
Outputs:
  FraudQueueUrl:
    Description: URL da fila SQS
    Value: !Ref FraudQueue

  FraudQueueArn:
    Description: ARN da fila SQS
    Value: !GetAtt FraudQueue.Arn

  FraudResultsTableName:
    Description: Tabela DynamoDB fraud-results
    Value: !Ref FraudResultsTable

  FraudAlertsTopicArn:
    Description: ARN do topico SNS de alertas
    Value: !Ref FraudAlertsTopic

  FraudScoringFunctionArn:
    Description: ARN da Lambda
    Value: !GetAtt FraudScoringFunction.Arn
